version: "3.8"

services:
  db:
    image: postgres:14.5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    ports:
      - 5425:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - db